config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :cryptos, only: [:index, :show] do
    resources :holdings, only: [:create, :update]
    resources :watchlists, only: [:create]
  end

  resources :holdings, only: [:index, :update]
  resources :watchlists, only: [:index, :destroy]

  get 'my_dashboard', to: 'holdings#index'
  get 'articles', to: 'pages#articles'
  get 'jargonbuster', to: 'pages#jargonbuster', as: 'jargon_buster'
  get :advance_date, to: 'holdings#advance_date', as: 'change_simulation'
  get :advance_date_week, to: 'holdings#advance_date_week', as: 'change_simulation_week'
  get :reset_holdings, to: 'holdings#reset_holdings', as: 'reset_holdings'
  # get :advance_date_index, to: 'holdings#advance_date_index', as: 'change_simulation_index'
  # get :advance_date_week_index, to: 'holdings#advance_date_week_index', as: 'change_simulation_week_index'
  # get :advance_date_show, to: 'holdings#advance_date_show', as: 'change_simulation_show'
  # get :advance_date_week_show, to: 'holdings#advance_date_week_show', as: 'change_simulation_week_show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <ul id="footer-list">
      <a href=""><li><i class="fab fa-github"></i></li></a>
      <a href=""><li><i class="fab fa-facebook"></i></li></a>
      <a href=""><li><i class="fab fa-twitter"></i></li></a>
      <a href=""><li><i class="fab fa-instagram"></i></li></a>
      <a href=""><li><i class="fab fa-linkedin"></i></li></a>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
<div class="sticky-top" id="navbar">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
      <%= link_to 'Cryptaul', root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarTogglerDemo02">
        <ul class="navbar-nav mb-2 mb-lg-0 align-items-center">
          <li class="nav-item">
            <%= link_to 'Dashboard', my_dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Watchlist', watchlists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Browse Cryptos', cryptos_path, class: "nav-link" %>
          </li>
          <li class="dropdown">
            <button class="dropbtn">Learn More</button>
            <div class="dropdown-content">
              <%= link_to 'Jargon Buster', jargon_buster_path%>
              <%= link_to 'Articles', articles_path%>
            </div>
          </li>
          <li class ="dropdown">
            <div class="dropdown">
              <button class="btn btn-basic dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                <img class="avatar-bordered nav-avatar" alt="avatar" src="https://kitt.lewagon.com/placeholder/users/solkarim91" />
              </button>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
                <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
                <li><%= link_to 'Reset Holdings',reset_holdings_path, data: { confirm: "Are you sure?" }, class: "dropdown-item" %></li>
              </ul>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
      <%# <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>
  <div class="simulation-navbar">
    <ul>
      <li style="margin-top:8px" class="col-sm">
        <h6>Simulation Date: <%= current_user.simulation_date.strftime('%d/%m/%Y') %></h6>
      </li>
      <div class="col-sm">
      <li>
        <%= link_to '+1 Day', change_simulation_path(current_user), style:'color:#FF840A', id:'date-sim-btn' %>
      </li>
      <li>
        <h6>|</h6>
      </li>
      <li>
        <%= link_to '+7 Days', change_simulation_week_path(current_user), style:'color:#FF840A', id:'date-sim-btn' %>
      </li>
      <li style="margin-left:20px">
        <h6 style="color:#FF840A">Balance: £<%= number_with_precision(current_user.balance, :precision => 2, :delimiter => ',') %></h6>
      </li>
      </div>
    </ul>
  </div>
</div>
<% else %>
<% end %>
    <% if params[:controller] == 'cryptos' && params[:action] == 'index' %>
    <script>
        document.addEventListener("DOMContentLoaded", function (event) {
            var scrollpos = sessionStorage.getItem('scrollpos');
            if (scrollpos) {
                window.scrollTo(0, scrollpos);
                sessionStorage.removeItem('scrollpos');
            }
        });

        window.addEventListener("beforeunload", function (e) {
            sessionStorage.setItem('scrollpos', window.scrollY);
        });
    </script>
  <% end %>