config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :cryptos, only: [:index, :show] do
    resources :holdings, only: [:create, :update]
    resources :watchlists, only: [:create]
  end

  resources :holdings, only: [:index, :update]
  resources :watchlists, only: [:index, :destroy]

  get 'my_dashboard', to: 'holdings#index'
  get 'articles', to: 'pages#articles'
  get 'jargonbuster', to: 'pages#jargonbuster', as: 'jargon_buster'
  get :advance_date, to: 'holdings#advance_date', as: 'change_simulation'
  get :advance_date_week, to: 'holdings#advance_date_week', as: 'change_simulation_week'
  get :reset_holdings, to: 'holdings#reset_holdings', as: 'reset_holdings'
  # get :advance_date_index, to: 'holdings#advance_date_index', as: 'change_simulation_index'
  # get :advance_date_week_index, to: 'holdings#advance_date_week_index', as: 'change_simulation_week_index'
  # get :advance_date_show, to: 'holdings#advance_date_show', as: 'change_simulation_show'
  # get :advance_date_week_show, to: 'holdings#advance_date_week_show', as: 'change_simulation_week_show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/crypto.rb
class Crypto < ApplicationRecord
  validates :name, presence: true
  validates :abbreviation, presence: true
  has_many :holdings
  has_many :watchlists
  has_many :histories, dependent: :destroy
  has_many :prices, through: :histories
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  require 'json'

  before_action :find_crypto, only: :show
  def index
    @watchlist = Watchlist.new
    @cryptos = Crypto.all

    # 24 hour percentage change
    @cryptos.each do |crypto|
      if crypto.histories.find_by(date: current_user.simulation_date)
        price_today = crypto.histories.find_by(date: current_user.simulation_date).price
        yesterday = current_user.simulation_date - 86_400
        if crypto.histories.find_by(date: yesterday).nil?
          crypto.previousdaypercentagechange = 0
        else
          price_yesterday = crypto.histories.find_by(date: yesterday).price
          crypto.price = price_today
          crypto.previousdaypercentagechange = ((price_today - price_yesterday) / price_yesterday) * 100
        end
      end
      crypto.save
    end
    @cryptos = @cryptos.sort_by { |crypto| crypto.id.to_i }
  end

  def show
    @holding = Holding.new
    @watchlist = Watchlist.new
  end

  private

  def find_crypto
    @crypto = Crypto.find(params[:id])
    current_date = current_user.simulation_date
    @price_data = @crypto.histories.where('date <= ?', current_date).map do |price|
      [price.date, price.price]
    end
    p @price_data
  end
end

app/views/cryptos/index.html.erb
<div class="browse-crypto-page">
  <div class= "container centered justify-content-center">
    <div class="banner-pages">
      <div class="main-title crypto-stats-title">
        <h1>Crypto Stats</h1>
      </div>
    </div>
    <table class='center table', id="cryptos-table", style="float:left mb-10">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Price</th>
          <th>24hr Change</th>
          <th class="graph-th"><span class="white-space">aaaaaaaaaaa</span>Graph<span class="white-space">aaaaaaaaaaa</span></th>
          <th>Watchlist</th>
        </tr>
      </thead>
      <tbody data-controller="clickableindex">
        <%counter = 0 %>
        <%@cryptos.each do |crypto| %>
          <tr data-link="<%=crypto_path(crypto)%>" data-clickableindex-target="cryptos" data-action="click->clickableindex#clickable" class = "clicking">
            <td>
              <%=counter += 1%>
            </td>
            <td>
              <%= link_to(image_tag(crypto.image), crypto_path(crypto),class: "crypto-image")%> <%=crypto.name%>
            </td>
            <td>
              £<%= number_with_precision(crypto.price, :precision => 2, :delimiter => ',') %>
            </td>
            <td>
              <% if crypto.previousdaypercentagechange.negative?() %>
                <div class = "red-font">
                  <%= number_with_precision(crypto.previousdaypercentagechange, :precision => 2, :delimiter => ',') %>%
                </div>
              <% else %>
                <div class = "green-font">
                  +<%= number_with_precision(crypto.previousdaypercentagechange, :precision => 2, :delimiter => ',')%>%
                </div>
              <% end %>
            </td>
            <td class="graph-td">
              <% @price_data = crypto.histories.where('date <= ?', current_user.simulation_date).map do |price| %>
                <% [price.date, price.price] %>
              <% end %>
              <div class="graph-img-cryptos">
                <%= line_chart @price_data, library: { vAxis: { baselineColor: '#FFFFFF', ticks: [] },
                hAxis: { ticks: [], baselineColor: '#FFFFFF', gridlines: { count: 0, color: 'white' }, textPosition: 'none' } }, points: false, colors: ['#EE841C'], height: "80px", width: "350px" %>
              </div>
            </td>
            <td>
              <% if crypto.watchlists.where(user: current_user).count > 0 %>
                <%= link_to watchlist_path(crypto.watchlists.first), method: :delete do %>
                  <i class="fas fa-heart" style="color: red;"></i>
                <% end %>
              <% else %>
                <%= simple_form_for [ crypto, @watchlist ] do |f| %>
                  <button name="button" type="submit" style="border: none;background: none;">
                    <i class="far fa-heart" style="color: red;"></i>
                  </button>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/cryptos/show.html.erb
<div class="container page-container">
  <!-- The Modal -->
  <div id="myModal" class="modal" data-controller="purchase-modal">
    <!-- Modal content -->
    <div class="modal-content center">
      <span class="close">&times;</span>
      <div class="title-exchange">
        <br>
        <h4 style='color'>Buy <%= @crypto.name%></h4>
        <p>1 <%= @crypto.name %> = £<strong data-purchase-modal-target="price"><%= '%.2f' % @crypto.histories.find_by(date: current_user.simulation_date).price %></strong></p>
        <p>Your balance is £<strong data-purchase-modal-target="balance"><%=  '%.2f' % current_user.balance %></strong><p>
        <p>Please select the number of <%= @crypto.name %> you'd like to purchase</p>
      </div>
      <%= simple_form_for [ @crypto, @holding ] do |f| %>
        <div id='modal-form'>
          <%= f.input :quantity, label: false, input_html: {data: {action: "change->purchase-modal#calculatePrice keyup->purchase-modal#calculatePrice", purchase_modal_target: "quantity"}} %>
          <%= f.submit 'Confirm Purchase', data: {purchase_modal_target: "confirm"}, class: "d-none", id: "confirm_link" %>
          <div id="sweet-alert-demo" class="buy-button banner-btn">Confirm Purchase</div>
        </div>
      <% end %>
      <br>
      <p data-purchase-modal-target="pounds" data-price="<%= '%.2f' % @crypto.histories.find_by(date: current_user.simulation_date).price %>" id="pounds">You're spending £0.00</p>
    </div>
  </div>

  <%# Graph and purchase container %>
  <div class="container graph-purchase-container">
    <%# Container for graph %>
    <div id="rounded-graph">
      <%= line_chart @price_data, library: { hAxis: { ticks: [], baselineColor: '#FFFFFF', gridlines: { count: 0, color: 'white' }, textPosition: 'none' } }, points: false, prefix: "£", round: 2, zeros: true, colors: ['#FF840A'], height: "390px" %>
    </div>
    <div id="rounded-graph-mobile">
      <%= line_chart @price_data, library: { hAxis: { ticks: [], baselineColor: '#FFFFFF', gridlines: { count: 0, color: 'white' }, textPosition: 'none' } }, points: false, prefix: "£", round: 2, zeros: true, colors: ['#FF840A'], height: "190px" %>
    </div>
    <%# Container for purchase area %>
    <div class="purchase-container">
    <%# Watchlist button %>
      <div id="watchlist-button">
        <% if @crypto.watchlists.where(user: current_user).count > 0 %>
          <%= link_to watchlist_path(@crypto.watchlists.first), method: :delete do %>
          <i class="fas fa-heart watchlist-icon" style="font-size: 24px; color: red;"></i>
          <% end %>
        <% else %>
          <%= simple_form_for [ @crypto, @watchlist ] do |f| %>
            <button name="button" type="submit" style="border: none;background: none; padding: 0">
            <i class="far fa-heart watchlist-icon" style="font-size: 24px; color: red;"></i>
            </button>
          <% end %>
        <% end %>
      </div>
      <div class="title">
        <h4><%= @crypto.name%></h4>
      </div>
      <div>
        <img class="rounded-circle"src="<%= @crypto.image %>" height="100px">
        <br><br>
      </div>
      <div>
        <p>1 <%= @crypto.name %> = £<%= number_with_precision(@crypto.histories.find_by(date: current_user.simulation_date).price, :precision => 2, :delimiter => ',') %></p>
      </div>
      <%# Container for buttons %>
      <div class="buy-button center">
        <button id="myBtn" type="button" class="buy-btn-filled"> Buy </button>
      </div>
    </div>
  </div>
  <div class="container product-info-container" data-controller="accordion">
    <div class="" data-accordion-target="content">
      <h4 class="">About</h4>
      <p><%= @crypto.name.capitalize %> is a decentralized
      <a href="<%= request.base_url + jargon_buster_path %>" data-toggle="tooltip" title="Blockchain can be described as a huge information file which lists all transactions that were ever made. Blockchain is the heart of the Bitcoin network and serves as a kind of a ledger. " data-original-title="Default tooltip">blockchain</a>
      platform that establishes a peer-to-peer network that securely executes and verifies application code, called smart contracts. Smart contracts allow participants to transact with each other without a trusted central authority.<br><br>By  <a href="<%= request.base_url + jargon_buster_path %>" data-toggle="tooltip" title="Mining is the backbone of a cryptocurrency network as it guarantees consensus among participants." data-original-title="Default tooltip">mining</a>, you can earn cryptocurrency without having to put down money for it. <%= @crypto.name.capitalize %> miners receive <%= @crypto.name.capitalize %> as a reward for completing  <a href="<%= request.base_url + jargon_buster_path %>" data-toggle="tooltip" title="A block records some piece of information that has not previously been entered into another block." data-original-title="Default tooltip">blocks</a> of verified transactions, which are added to the blockchain.<br><br>Each <%= @crypto.name.capitalize %> is basically a computer file which is stored in a 'digital wallet' containing your <a href="<%= request.base_url + jargon_buster_path %>" data-toggle="tooltip" title=" Your digital identity is made up of every piece of information about you on the internet, that when added together paints a picture of “you”." data-original-title="Default tooltip">Digital identity</a> on a smartphone or computer. People can send <%= @crypto.name.capitalize %>s (or part of one) to your digital wallet, and you can send <%= @crypto.name.capitalize %>s to other people. Every single transaction is recorded in a public list called the blockchain. This makes it possible to trace the history of Bitcoins to stop people from spending coins they do not own, making copies or undo-ing transactions.</p>
    </div>
  </div>
</div>